# Generated by Django 5.0.4 on 2025-02-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_coupon_remove_order_email_order_date_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
