# Generated by Django 5.0.4 on 2025-02-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
