# Generated by Django 5.1.4 on 2025-01-13 18:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='bronchure',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.png', max_length=255),
        ),
    ]
