# Generated by Django 5.1.4 on 2025-01-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_search_vector_manufacturer_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bronchure',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
